requires 'DBIx::Sunny';
requires 'DBD::mysql', '<= 4.046';
requires 'JSON::XS', '3.00';
requires 'Kossy';
requires 'Plack::Builder';
requires 'Plack::Session';
requires 'Starlet';
requires 'Time::Moment';
requires 'Redis::Fast';
requires 'Gazelle';
requires 'Monoceros';
requires 'HTTP::Parser::XS';
requires 'HTTP::Headers::Fast';
requires 'EV';
requires 'Server::Starter';

on configure => sub {
    requires 'ExtUtils::MakeMaker';
};

on test => sub {
    requires 'Test::More';
};
